name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Create virtual environment
      run: uv venv
    - name: Install build dependencies
      run: uv pip install hatchling twine
    - name: Build package
      run: uv build
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PAT }}
      run: |
        uv run twine upload --repository-url https://ghcr.io/v2/${{ github.repository }}/pypi/upload dist/*
    - name: Debug on failure
      if: failure()
      run: |
        ls -la dist/
        echo "Repository URL used: https://ghcr.io/v2/${{ github.repository }}/pypi/upload"